### ISSUE TITLE
Decorator doesn't actually seem to work

### ISSUE THREAD

**Issue by harrislapiroff** [harrislapiroff/wagtail-foliage#4]
`page_tree` didn't work as a decorator in my last test, which looked something like this:

```python
class EmailPageTestCase(TestCase):
    @page_tree(PAGE_TREE)
    def test_no_auto_generated_header(self):
        pass
```

I got this traceback:

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 163, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'root_page'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/contextlib.py", line 29, in inner
    with self._recreate_cm():
  File "/usr/local/lib/python3.5/site-packages/foliage/contextmanagers.py", line 22, in __enter__
    old_root_page = self.site.root_page
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 177, in __get__
    rel_obj = self.get_object(instance)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 144, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
wagtail.core.models.Page.DoesNotExist: Page matching query does not exist.
```

Confusingly, it did work when used as a context manager:

```python
class EmailPageTestCase(TestCase):
    def test_no_auto_generated_header(self):
        with page_tree(PAGE_TREE):
            pass
```

My best guess is somehow the default Wagtail site tree isn't available outside of the method, but is available inside of it?

**Comment by chosak** [comment]
@harrislapiroff I believe this error occurs because using `@page_tree` as a decorator on the test method causes its `__enter__` code to be executed _at import time_, before the database is ready or populated. The context manager approach works because the database is set up before the tests begin running.
